<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.29xhdQH' shared service.

return $this->privates['.service_locator.29xhdQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'arrayAllCustomers' => ['privates', 'App\\Service\\TreatmensCustomers', 'getTreatmensCustomersService.php', true],
    'arrayJson1' => ['privates', 'App\\Service\\InputPhpJsonFile', 'getInputPhpJsonFileService.php', true],
], [
    'arrayAllCustomers' => 'App\\Service\\TreatmensCustomers',
    'arrayJson1' => 'App\\Service\\InputPhpJsonFile',
]);
