<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NuGdx.h' shared service.

return $this->privates['.service_locator.NuGdx.h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\DisplayController::alltransaction' => ['privates', '.service_locator.WM7O2D6', 'get_ServiceLocator_WM7O2D6Service.php', true],
    'App\\Controller\\DisplayController::displayfivetransaction' => ['privates', '.service_locator.CODoEAj', 'get_ServiceLocator_CODoEAjService.php', true],
    'App\\Controller\\DisplayController::displayten' => ['privates', '.service_locator.29xhdQH', 'get_ServiceLocator_29xhdQHService.php', true],
    'App\\Controller\\DisplayController:alltransaction' => ['privates', '.service_locator.WM7O2D6', 'get_ServiceLocator_WM7O2D6Service.php', true],
    'App\\Controller\\DisplayController:displayfivetransaction' => ['privates', '.service_locator.CODoEAj', 'get_ServiceLocator_CODoEAjService.php', true],
    'App\\Controller\\DisplayController:displayten' => ['privates', '.service_locator.29xhdQH', 'get_ServiceLocator_29xhdQHService.php', true],
], [
    'App\\Controller\\DisplayController::alltransaction' => '?',
    'App\\Controller\\DisplayController::displayfivetransaction' => '?',
    'App\\Controller\\DisplayController::displayten' => '?',
    'App\\Controller\\DisplayController:alltransaction' => '?',
    'App\\Controller\\DisplayController:displayfivetransaction' => '?',
    'App\\Controller\\DisplayController:displayten' => '?',
]);
