<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\TreatmensCustomers' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\TreatmensCustomers.php';

return $this->privates['App\\Service\\TreatmensCustomers'] = new \App\Service\TreatmensCustomers();
