<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Xmz4P_k' shared service.

return $this->privates['.service_locator.Xmz4P_k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\DisplayController::alltransaction' => ['privates', '.service_locator.WM7O2D6', 'get_ServiceLocator_WM7O2D6Service.php', true],
    'App\\Controller\\DisplayController:alltransaction' => ['privates', '.service_locator.WM7O2D6', 'get_ServiceLocator_WM7O2D6Service.php', true],
], [
    'App\\Controller\\DisplayController::alltransaction' => '?',
    'App\\Controller\\DisplayController:alltransaction' => '?',
]);
