<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'display' => [[], ['_controller' => 'App\\Controller\\DisplayController::alltransaction'], [], [['text', '/display']], [], []],
    'displayten' => [[], ['_controller' => 'App\\Controller\\DisplayController::displayten'], [], [['text', '/displayten']], [], []],
    'displayfivetransaction' => [[], ['_controller' => 'App\\Controller\\DisplayController::displayfivetransaction'], [], [['text', '/displayfive']], [], []],
    'general' => [[], ['_controller' => 'App\\Controller\\GeneralController::index'], [], [['text', '/']], [], []],
];
